version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: game_api
      POSTGRES_PASSWORD: ApiGame2024#
      POSTGRES_DB: game
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: game_api
      DATABASE_PASSWORD: ApiGame2024#
      DATABASE_NAME: game
